# Generated by Django 3.1.12 on 2025-01-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20250110_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjongoFAQ',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
