# Generated by Django 3.1.12 on 2025-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20250122_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uni_rollno', models.CharField(max_length=10)),
                ('stream', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
    ]
