# Generated by Django 3.1.12 on 2025-01-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20250122_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busid', models.CharField(max_length=10)),
                ('bus_no', models.CharField(max_length=10)),
                ('route_from', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('staff_incharge', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('staff_phone', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=100)),
                ('fee_to_each_location', models.JSONField()),
                ('distance_to_each_location', models.JSONField()),
                ('time_to_each_destination', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
